### PR TITLE
Change static properties to var make solution more dynamic

### PR DESCRIPTION
**Pull request by minenordlicht**
Change static properties to var make solution more dynamic for On-premise hosted Virgil backend services

### CODE REVIEW

**Comment by Scratch-net** [comment]
Why not make a custom cardVerifier that suits your needs? @minenordlicht

**Comment by minenordlicht** [comment]
Hi @Scratch-net, please check this pull request. As far there is static access for constants, this make solution for card verification for On-premise hosted Virgil backend services. Thanks

**Comment by minenordlicht** [comment]
> Why not make a custom cardVerifier that suits your needs? @minenordlicht
@Scratch-net  It is not possible. I can make copy of this class and rewrite this line, but It is not possible to pass it into card verifier.
Also it is not possible to create custom EThree object because many constructors inside init method are private or internal, so they are not accessible outside of library (e.g. LocalKeyStorage, CloudKeyManager, SQLiteCardStorage, LookupManager, CloudRatchetStorage....)

**Comment by Scratch-net** [comment]
Accepting this PR won't solve your problems, right? You would still need a new library version on cocoaPods?

**Comment by minenordlicht** [comment]
> Accepting this PR won't solve your problems, right? You would still need a new library version on cocoaPods?

It will solve issue. Ideally, it will be nice to have normal release lets say version v8.2.1.
Then also virgil-e3kit-x needs to have update dependency to this version.

**Comment by Scratch-net** [comment]
Ok, let's start with merging this PR and see what we can do else a bit later

**Review by Scratch-net — APPROVED** [review]

**Comment by minenordlicht** [comment]
> Ok, let's start with merging this PR and see what we can do else a bit later

Thanks. 
If you create new release of this library v8.2.1, I can prepare PR with updated dependencies for CocoaPods and SPM in libraries which used this as dependency. It is libraries:
- https://github.com/VirgilSecurity/virgil-ratched-x
- https://github.com/VirgilSecurity/virgil-pythia-x

**Comment by Scratch-net** [comment]
Hey @minenordlicht I think this and other dependent packages were updated. Could you please check?

**Pull request merged**
